/*
 *
 * UsersPage constants
 *
 */

export const GET_FILTERED_USERS_START = 'GET_FILTERED_USERS_START';
export const GET_FILTERED_USERS_SUCCESS = 'GET_FILTERED_USERS_SUCCESS';
export const GET_FILTERED_USERS_FAILED = 'GET_FILTERED_USERS_FAILED';
export const GET_GROUP_TAGS_START = 'GET_GROUP_TAGS_START';
export const GET_GROUP_TAGS_SUCCESS = 'GET_GROUP_TAGS_SUCCESS';
export const GET_GROUP_TAGS_FAILED = 'GET_GROUP_TAGS_FAILED';
