/*
 *
 * ResetPasswordAcceptedPage constants
 *
 */

export const SEND_RESET_PASSWORD_INFO_START = 'SEND_RESET_PASSWORD_INFO_START';
export const SEND_RESET_PASSWORD_INFO_SUCCESS = 'SEND_RESET_PASSWORD_INFO_SUCCESS';
export const SEND_RESET_PASSWORD_INFO_FAILED = 'SEND_RESET_PASSWORD_INFO_FAILED';
