/*
 *
 * HomePage constants
 *
 */

export const GET_UNASSEMBLED_GROUPS_START = 'GET_UNASSEMBLED_GROUPS_START';
export const GET_UNASSEMBLED_GROUPS_SUCCESS = 'GET_UNASSEMBLED_GROUPS_SUCCESS';
export const GET_UNASSEMBLED_GROUPS_FAILED = 'GET_UNASSEMBLED_GROUPS_FAILED';

export const GET_ASSEMBLED_GROUPS_START = 'GET_ASSEMBLED_GROUPS_START';
export const GET_ASSEMBLED_GROUPS_SUCCESS = 'GET_ASSEMBLED_GROUPS_SUCCESS';
export const GET_ASSEMBLED_GROUPS_FAILED = 'GET_ASSEMBLED_GROUPS_FAILED';
