/*
 *
 * ProfilePage constants
 *
 */

// export const GET_CURRENT_USER = 'GET_CURRENT_USER';
// export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
// export const GET_CURRENT_USER_FAILED = 'GET_CURRENT_USER_FAILED';
export const GET_CURRENT_USER_GROUPS = 'GET_CURRENT_USER_GROUPS';
export const GET_CURRENT_USER_GROUPS_SUCCESS = 'GET_CURRENT_USER_GROUPS_SUCCESS';
export const GET_CURRENT_USER_GROUPS_FAILED = 'GET_CURRENT_USER_GROUPS_FAILED';
