/*
 *
 * ProfilePage constants
 *
 */

// export const GET_CURRENT_USER = 'GET_CURRENT_USER';
// export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
// export const GET_CURRENT_USER_FAILED = 'GET_CURRENT_USER_FAILED';
export const GET_CURRENT_USER_GROUPS = 'GET_CURRENT_USER_GROUPS';
export const GET_CURRENT_USER_GROUPS_SUCCESS = 'GET_CURRENT_USER_GROUPS_SUCCESS';
export const GET_CURRENT_USER_GROUPS_FAILED = 'GET_CURRENT_USER_GROUPS_FAILED';

export const EDIT_NAME = 'EDIT_NAME';
export const EDIT_NAME_SUCCESS = 'EDIT_NAME_SUCCESS';
export const EDIT_NAME_FAILED = 'EDIT_NAME_FAILED';

export const EDIT_ABOUT_USER_INFO = 'EDIT_ABOUT_USER_INFO';
export const EDIT_ABOUT_USER_INFO_SUCCESS = 'EDIT_ABOUT_USER_INFO_SUCCESS';
export const EDIT_ABOUT_USER_INFO_FAILED = 'EDIT_ABOUT_USER_INFO_FAILED';

export const EDIT_GENDER = 'EDIT_GENDER';
export const EDIT_GENDER_SUCCESS = 'EDIT_GENDER_SUCCESS';
export const EDIT_GENDER_FAILED = 'EDIT_GENDER_FAILED';

export const EDIT_BIRTH_YEAR = 'EDIT_BIRTH_YEAR';
export const EDIT_BIRTH_YEAR_SUCCESS = 'EDIT_BIRTH_YEAR_SUCCESS';
export const EDIT_BIRTH_YEAR_FAILED = 'EDIT_BIRTH_YEAR_FAILED';
