/*
 *
 * ProfilePage constants
 *
 */

// export const GET_CURRENT_USER = 'GET_CURRENT_USER';
// export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
// export const GET_CURRENT_USER_FAILED = 'GET_CURRENT_USER_FAILED';
export const GET_CURRENT_USER_GROUPS = 'GET_CURRENT_USER_GROUPS';
export const GET_CURRENT_USER_GROUPS_SUCCESS = 'GET_CURRENT_USER_GROUPS_SUCCESS';
export const GET_CURRENT_USER_GROUPS_FAILED = 'GET_CURRENT_USER_GROUPS_FAILED';

export const EDIT_PROFILE_START = 'EDIT_PROFILE_START';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILED = 'EDIT_PROFILE_FAILED';

export const EDIT_NAME = 'EDIT_NAME';
export const EDIT_NAME_SUCCESS = 'EDIT_NAME_SUCCESS';
export const EDIT_NAME_FAILED = 'EDIT_NAME_FAILED';

export const EDIT_ABOUT_USER_INFO = 'EDIT_ABOUT_USER_INFO';
export const EDIT_ABOUT_USER_INFO_SUCCESS = 'EDIT_ABOUT_USER_INFO_SUCCESS';
export const EDIT_ABOUT_USER_INFO_FAILED = 'EDIT_ABOUT_USER_INFO_FAILED';

export const EDIT_GENDER = 'EDIT_GENDER';
export const EDIT_GENDER_SUCCESS = 'EDIT_GENDER_SUCCESS';
export const EDIT_GENDER_FAILED = 'EDIT_GENDER_FAILED';

export const EDIT_BIRTH_YEAR = 'EDIT_BIRTH_YEAR';
export const EDIT_BIRTH_YEAR_SUCCESS = 'EDIT_BIRTH_YEAR_SUCCESS';
export const EDIT_BIRTH_YEAR_FAILED = 'EDIT_BIRTH_YEAR_FAILED';

export const EDIT_CONTACTS = 'EDIT_CONTACTS';
export const EDIT_CONTACTS_SUCCESS = 'EDIT_CONTACTS_SUCCESS';
export const EDIT_CONTACTS_FAILED = 'EDIT_CONTACTS_FAILED';

export const MAKE_TEACHER = 'MAKE_TEACHER';
export const MAKE_TEACHER_SUCCESS = 'MAKE_TEACHER_SUCCESS';
export const MAKE_TEACHER_FAILED = 'MAKE_TEACHER_FAILED';

export const MAKE_NOT_TEACHER = 'MAKE_NOT_TEACHER';
export const MAKE_NOT_TEACHER_SUCCESS = 'MAKE_NOT_TEACHER_SUCCESS';
export const MAKE_NOT_TEACHER_FAILED = 'MAKE_NOT_TEACHER_FAILED';

export const EDIT_SKILLS_START = 'EDIT_SKILLS_START';
export const EDIT_SKILLS_SUCCESS = 'EDIT_SKILLS_SUCCESS';
export const EDIT_SKILLS_FAILED = 'EDIT_SKILLS_FAILED';

export const MAKE_REPORT_START = 'MAKE_REPORT_START';
export const MAKE_REPORT_SUCCESS = 'MAKE_REPORT_SUCCESS';
export const MAKE_REPORT_FAILED = 'MAKE_REPORT_FAILED';

export const GET_GROUP_TAGS_START = 'GET_GROUP_TAGS_START';
export const GET_GROUP_TAGS_SUCCESS = 'GET_GROUP_TAGS_SUCCESS';
export const GET_GROUP_TAGS_FAILED = 'GET_GROUP_TAGS_FAILED';
