/*
 *
 * NotificationPage constants
 *
 */

export const CHANGE_INVITATION_STATUS_START = 'CHANGE_INVITATION_STATUS_START';
export const CHANGE_INVITATION_STATUS_SUCCESS = 'CHANGE_INVITATION_STATUS_SUCCESS';
export const CHANGE_INVITATION_STATUS_FAILED = 'CHANGE_INVITATION_STATUS_FAILED';
export const GET_NOTIFIES_START = 'GET_NOTIFIES_START';
export const GET_NOTIFIES_SUCCESS = 'GET_NOTIFIES_SUCCESS';
export const GET_NOTIFIES_FAILED = 'GET_NOTIFIES_FAILED';
export const GET_INVITES_START = 'GET_INVITES_START';
export const GET_INVITES_SUCCESS = 'GET_INVITES_SUCCESS';
export const GET_INVITES_FAILED = 'GET_INVITES_FAILED';
export const DOWNLOAD_COURSE_PLAN_START = 'DOWNLOAD_COURSE_PLAN_START';
export const DOWNLOAD_COURSE_PLAN_SUCCESS = 'DOWNLOAD_COURSE_PLAN_SUCCESS';
export const DOWNLOAD_COURSE_PLAN_FAILED = 'DOWNLOAD_COURSE_PLAN_FAILED';
export const GET_NOTIFIES_SETTINGS_START = 'GET_NOTIFIES_SETTINGS_START';
export const GET_NOTIFIES_SETTINGS_SUCCESS = 'GET_NOTIFIES_SETTINGS_SUCCESS';
export const GET_NOTIFIES_SETTINGS_FAILED = 'GET_NOTIFIES_SETTINGS_FAILED';
export const SET_NOTIFY_SETTING_START = 'SET_NOTIFY_SETTING_START';
export const SET_NOTIFY_SETTING_SUCCESS = 'SET_NOTIFY_SETTING_SUCCESS';
export const SET_NOTIFY_SETTING_FAILED = 'SET_NOTIFY_SETTING_FAILED';
