/*
 *
 * NotificationPage constants
 *
 */

export const CHANGE_INVITATION_STATUS_START = 'CHANGE_INVITATION_STATUS_START';
export const CHANGE_INVITATION_STATUS_SUCCESS = 'CHANGE_INVITATION_STATUS_SUCCESS';
export const CHANGE_INVITATION_STATUS_FAILED = 'CHANGE_INVITATION_STATUS_FAILED';
export const GET_NOTIFIES_START = 'GET_NOTIFIES_START';
export const GET_NOTIFIES_SUCCESS = 'GET_NOTIFIES_SUCCESS';
export const GET_NOTIFIES_FAILED = 'GET_NOTIFIES_FAILED';
export const GET_INVITES_START = 'GET_INVITES_START';
export const GET_INVITES_SUCCESS = 'GET_INVITES_SUCCESS';
export const GET_INVITES_FAILED = 'GET_INVITES_FAILED';
export const DOWNLOAD_COURSE_FILE_START = 'DOWNLOAD_COURSE_FILE_START';
export const DOWNLOAD_COURSE_FILE_SUCCESS = 'DOWNLOAD_COURSE_FILE_SUCCESS';
export const DOWNLOAD_COURSE_FILE_FAILED = 'DOWNLOAD_COURSE_FILE_FAILED';
