/*
 *
 * NotificationPage constants
 *
 */

export const CHANGE_INVITATION_STATUS_START = 'CHANGE_INVITATION_STATUS_START';
export const CHANGE_INVITATION_STATUS_SUCCESS = 'CHANGE_INVITATION_STATUS_SUCCESS';
export const CHANGE_INVITATION_STATUS_FAILED = 'CHANGE_INVITATION_STATUS_FAILED';
