//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduHubLibrary.Mailing {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageThemes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageThemes() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EduHubLibrary.Mailing.MessageThemes", typeof(MessageThemes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приглашение на роль администратора.
        /// </summary>
        internal static string AdminInvitation {
            get {
                return ResourceManager.GetString("AdminInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Курс завершен.
        /// </summary>
        internal static string CourseFinished {
            get {
                return ResourceManager.GetString("CourseFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Принят учебный план.
        /// </summary>
        internal static string CurriculumAccepted {
            get {
                return ResourceManager.GetString("CurriculumAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Учебный план отклонен.
        /// </summary>
        internal static string CurriculumDeclined {
            get {
                return ResourceManager.GetString("CurriculumDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предложен учебный план.
        /// </summary>
        internal static string CurriculumSuggested {
            get {
                return ResourceManager.GetString("CurriculumSuggested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группа сформирована.
        /// </summary>
        internal static string GroupIsFormed {
            get {
                return ResourceManager.GetString("GroupIsFormed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Принято приглашение.
        /// </summary>
        internal static string InvitationAccepted {
            get {
                return ResourceManager.GetString("InvitationAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приглашение отклонено.
        /// </summary>
        internal static string InvitationDeclined {
            get {
                return ResourceManager.GetString("InvitationDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получено приглашение.
        /// </summary>
        internal static string InvitationReceived {
            get {
                return ResourceManager.GetString("InvitationReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь покинул группу.
        /// </summary>
        internal static string MemberLeft {
            get {
                return ResourceManager.GetString("MemberLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приглашение на роль модератора.
        /// </summary>
        internal static string ModeratorInvitation {
            get {
                return ResourceManager.GetString("ModeratorInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый руководитель группы.
        /// </summary>
        internal static string NewCreator {
            get {
                return ResourceManager.GetString("NewCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый член группы.
        /// </summary>
        internal static string NewMember {
            get {
                return ResourceManager.GetString("NewMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новое уведомление.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новая жалоба.
        /// </summary>
        internal static string ReportMessage {
            get {
                return ResourceManager.GetString("ReportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение пароля.
        /// </summary>
        internal static string RestorePassword {
            get {
                return ResourceManager.GetString("RestorePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый отзыв.
        /// </summary>
        internal static string ReviewReceived {
            get {
                return ResourceManager.GetString("ReviewReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новая санкция.
        /// </summary>
        internal static string SanctionsAppliedForAdmin {
            get {
                return ResourceManager.GetString("SanctionsAppliedForAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новая санкция.
        /// </summary>
        internal static string SanctionsAppliedForUser {
            get {
                return ResourceManager.GetString("SanctionsAppliedForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Санкция отменена.
        /// </summary>
        internal static string SanctionsCancelledForAdmin {
            get {
                return ResourceManager.GetString("SanctionsCancelledForAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Санкция отменена.
        /// </summary>
        internal static string SanctionsCancelledForUser {
            get {
                return ResourceManager.GetString("SanctionsCancelledForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Преподаватель утвержден.
        /// </summary>
        internal static string TeacherFound {
            get {
                return ResourceManager.GetString("TeacherFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение почты.
        /// </summary>
        internal static string UserConfirmation {
            get {
                return ResourceManager.GetString("UserConfirmation", resourceCulture);
            }
        }
    }
}
