/*
 *
 * AdminPage constants
 *
 */

export const INVITE_MODERATOR_START = 'INVITE_MODERATOR_START';
export const INVITE_MODERATOR_SUCCESS = 'INVITE_MODERATOR_SUCCESS';
export const INVITE_MODERATOR_FAILED = 'INVITE_MODERATOR_FAILED';
export const DELETE_MODERATOR_START = 'DELETE_MODERATOR_START';
export const DELETE_MODERATOR_SUCCESS = 'DELETE_MODERATOR_SUCCESS';
export const DELETE_MODERATOR_FAILED = 'DELETE_MODERATOR_FAILED';
export const APPLY_SANCTION_START = 'APPLY_SANCTION_START';
export const APPLY_SANCTION_SUCCESS = 'APPLY_SANCTION_SUCCESS';
export const APPLY_SANCTION_FAILED = 'APPLY_SANCTION_FAILED';
export const ANNUL_SANCTION_START = 'ANNUL_SANCTION_START';
export const ANNUL_SANCTION_SUCCESS = 'ANNUL_SANCTION_SUCCESS';
export const ANNUL_SANCTION_FAILED = 'ANNUL_SANCTION_FAILED';
export const SEARCH_USERS_START = 'SEARCH_USERS_START';
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const SEARCH_USERS_FAILED = 'SEARCH_USERS_FAILED';
export const GET_MODERS_START = 'GET_MODERS_START';
export const GET_MODERS_SUCCESS = 'GET_MODERS_SUCCESS';
export const GET_MODERS_FAILED = 'GET_MODERS_FAILED';
export const GET_REPORTS_START = 'GET_REPORTS_START';
export const GET_REPORTS_SUCCESS = 'GET_REPORTS_SUCCESS';
export const GET_REPORTS_FAILED = 'GET_REPORTS_FAILED';
export const GET_SANCTIONS_START = 'GET_SANCTIONS_START';
export const GET_SANCTIONS_SUCCESS = 'GET_SANCTIONS_SUCCESS';
export const GET_SANCTIONS_FAILED = 'GET_SANCTIONS_FAILED';
export const GET_ADMIN_HISTORY_START = 'GET_ADMIN_HISTORY_START';
export const GET_ADMIN_HISTORY_SUCCESS = 'GET_ADMIN_HISTORY_SUCCESS';
export const GET_ADMIN_HISTORY_FAILED = 'GET_ADMIN_HISTORY_FAILED';
export const GET_CURRENT_REPORT_START = 'GET_CURRENT_REPORT_START';
export const GET_CURRENT_REPORT_SUCCESS = 'GET_CURRENT_REPORT_SUCCESS';
export const GET_CURRENT_REPORT_FAILED = 'GET_CURRENT_REPORT_FAILED';
export const GET_CURRENT_SANCTION_START = 'GET_CURRENT_SANCTION_START';
export const GET_CURRENT_SANCTION_SUCCESS = 'GET_CURRENT_SANCTION_SUCCESS';
export const GET_CURRENT_SANCTION_FAILED = 'GET_CURRENT_SANCTION_FAILED';



