/*
 *
 * AdminPage constants
 *
 */

export const INVITE_MODERATOR_START = 'INVITE_MODERATOR_START';
export const INVITE_MODERATOR_SUCCESS = 'INVITE_MODERATOR_SUCCESS';
export const INVITE_MODERATOR_FAILED = 'INVITE_MODERATOR_FAILED';
export const DELETE_MODERATOR_START = 'DELETE_MODERATOR_START';
export const DELETE_MODERATOR_SUCCESS = 'DELETE_MODERATOR_SUCCESS';
export const DELETE_MODERATOR_FAILED = 'DELETE_MODERATOR_FAILED';
export const APPLY_SANCTION_START = 'APPLY_SANCTION_START';
export const APPLY_SANCTION_SUCCESS = 'APPLY_SANCTION_SUCCESS';
export const APPLY_SANCTION_FAILED = 'APPLY_SANCTION_FAILED';
export const ANNUL_SANCTION_START = 'ANNUL_SANCTION_START';
export const ANNUL_SANCTION_SUCCESS = 'ANNUL_SANCTION_SUCCESS';
export const ANNUL_SANCTION_FAILED = 'ANNUL_SANCTION_FAILED';
export const SEARCH_USERS_START = 'SEARCH_USERS_START';
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const SEARCH_USERS_FAILED = 'SEARCH_USERS_FAILED';

