/*
 *
 * GroupsPage constants
 *
 */

export const GET_FILTERED_GROUPS_START = 'GET_FILTERED_GROUPS_START';
export const GET_FILTERED_GROUPS_SUCCESS = 'GET_FILTERED_GROUPS_SUCCESS';
export const GET_FILTERED_GROUPS_ERROR = 'GET_FILTERED_GROUPS_ERROR';
export const GET_GROUP_TAGS_START = 'GET_GROUP_TAGS_START';
export const GET_GROUP_TAGS_SUCCESS = 'GET_GROUP_TAGS_SUCCESS';
export const GET_GROUP_TAGS_FAILED = 'GET_GROUP_TAGS_FAILED';
