/*
 *
 * GroupsPage constants
 *
 */

export const GET_FILTERED_GROUPS_START = 'GET_FILTERED_GROUPS_START';
export const GET_FILTERED_GROUPS_SUCCESS = 'GET_FILTERED_GROUPS_SUCCESS';
export const GET_FILTERED_GROUPS_ERROR = 'GET_FILTERED_GROUPS_ERROR';
