/*
 *
 * GroupsPage constants
 *
 */

export const GET_UNASSEMBLED_GROUPS_START = 'GET_UNASSEMBLED_GROUPS_START';
export const GET_UNASSEMBLED_GROUPS_SUCCESS = 'GET_UNASSEMBLED_GROUPS_SUCCESS';
export const GET_UNASSEMBLED_GROUPS_ERROR = 'GET_UNASSEMBLED_GROUPS_ERROR';

export const GET_ASSEMBLED_GROUPS_START = 'GET_ASSEMBLED_GROUPS_START';
export const GET_ASSEMBLED_GROUPS_SUCCESS = 'GET_ASSEMBLED_GROUPS_SUCCESS';
export const GET_ASSEMBLED_GROUPS_ERROR = 'GET_ASSEMBLED_GROUPS_ERROR';
