/*
 *
 * GroupPage constants
 *
 */

export const ENTER_GROUP_START = 'ENTER_GROUP_START';
export const ENTER_GROUP_SUCCESS = 'ENTER_GROUP_SUCCESS';
export const ENTER_GROUP_FAILED = 'ENTER_GROUP_FAILED';
export const LEAVE_GROUP_START = 'LEAVE_GROUP_START';
export const LEAVE_GROUP_SUCCESS = 'LEAVE_GROUP_SUCCESS';
export const LEAVE_GROUP_FAILED = 'LEAVE_GROUP_FAILED';
export const INVITE_MEMBER_START = 'INVITE_MEMBER_START';
export const INVITE_MEMBER_SUCCESS = 'INVITE_MEMBER_SUCCESS';
export const INVITE_MEMBER_FAILED = 'INVITE_MEMBER_FAILED';
export const GET_INVITATION_USERS_START = 'GET_INVITATION_USERS_START';
export const GET_INVITATION_USERS_SUCCESS = 'GET_INVITATION_USERS_SUCCESS';
export const GET_INVITATION_USERS_FAILED = 'GET_INVITATION_USERS_FAILED';
