/*
 *
 * GroupPage constants
 *
 */

export const ENTER_GROUP_START = 'ENTER_GROUP_START';
export const ENTER_GROUP_SUCCESS = 'ENTER_GROUP_SUCCESS';
export const ENTER_GROUP_FAILED = 'ENTER_GROUP_FAILED';
export const LEAVE_GROUP_START = 'LEAVE_GROUP_START';
export const LEAVE_GROUP_SUCCESS = 'LEAVE_GROUP_SUCCESS';
export const LEAVE_GROUP_FAILED = 'LEAVE_GROUP_FAILED';
export const INVITE_MEMBER_START = 'INVITE_MEMBER_START';
export const INVITE_MEMBER_SUCCESS = 'INVITE_MEMBER_SUCCESS';
export const INVITE_MEMBER_FAILED = 'INVITE_MEMBER_FAILED';
export const EDIT_GROUP_TITLE = 'EDIT_GROUP_TITLE';
export const EDIT_GROUP_TITLE_SUCCESS = 'EDIT_GROUP_TITLE_SUCCESS';
export const EDIT_GROUP_TITLE_FAILED = 'EDIT_GROUP_TITLE_FAILED';
export const EDIT_GROUP_DESCRIPTION = 'EDIT_GROUP_DESCRIPTION';
export const EDIT_GROUP_DESCRIPTION_SUCCESS = 'EDIT_GROUP_DESCRIPTION_SUCCESS';
export const EDIT_GROUP_DESCRIPTION_FAILED = 'EDIT_GROUP_DESCRIPTION_FAILED';
export const EDIT_GROUP_TAGS = 'EDIT_GROUP_TAGS';
export const EDIT_GROUP_TAGS_SUCCESS = 'EDIT_GROUP_TAGS_SUCCESS';
export const EDIT_GROUP_TAGS_FAILED = 'EDIT_GROUP_TAGS_FAILED';
export const EDIT_GROUP_SIZE = 'EDIT_GROUP_SIZE';
export const EDIT_GROUP_SIZE_SUCCESS = 'EDIT_GROUP_SIZE_SUCCESS';
export const EDIT_GROUP_SIZE_FAILED = 'EDIT_GROUP_SIZE_FAILED';
export const EDIT_GROUP_PRICE = 'EDIT_GROUP_PRICE';
export const EDIT_GROUP_PRICE_SUCCESS = 'EDIT_GROUP_PRICE_SUCCESS';
export const EDIT_GROUP_PRICE_FAILED = 'EDIT_GROUP_PRICE_FAILED';
export const EDIT_GROUP_TYPE = 'EDIT_GROUP_TYPE';
export const EDIT_GROUP_TYPE_SUCCESS = 'EDIT_GROUP_TYPE_SUCCESS';
export const EDIT_GROUP_TYPE_FAILED = 'EDIT_GROUP_TYPE_FAILED';
export const EDIT_GROUP_PRIVACY = 'EDIT_GROUP_PRIVACY';
export const EDIT_GROUP_PRIVACY_SUCCESS = 'EDIT_GROUP_PRIVACY_SUCCESS';
export const EDIT_GROUP_PRIVACY_FAILED = 'EDIT_GROUP_PRIVACY_FAILED';
export const SEARCH_INVITATION_MEMBER = 'SEARCH_INVITATION_MEMBER';
export const SEARCH_INVITATION_MEMBER_SUCCESS = 'SEARCH_INVITATION_MEMBER_SUCCESS';
export const SEARCH_INVITATION_MEMBER_FAILED = 'SEARCH_INVITATION_MEMBER_FAILED';
export const ADD_PLAN_START = 'ADD_PLAN_START';
export const ADD_PLAN_SUCCESS = 'ADD_PLAN_SUCCESS';
export const ADD_PLAN_FAILED = 'ADD_PLAN_FAILED';
export const ACCEPT_PLAN_START = 'ACCEPT_PLAN_START';
export const ACCEPT_PLAN_SUCCESS = 'ACCEPT_PLAN_SUCCESS';
export const ACCEPT_PLAN_FAILED = 'ACCEPT_PLAN_FAILED';
export const DECLINE_PLAN_START = 'DECLINE_PLAN_START';
export const DECLINE_PLAN_SUCCESS = 'DECLINE_PLAN_SUCCESS';
export const DECLINE_PLAN_FAILED = 'DECLINE_PLAN_FAILED';
export const GET_CURRENT_PLAN_START = 'GET_CURRENT_PLAN_START';
export const GET_CURRENT_PLAN_SUCCESS = 'GET_CURRENT_PLAN_SUCCESS';
export const GET_CURRENT_PLAN_FAILED = 'GET_CURRENT_PLAN_FAILED';
export const GET_CURRENT_CHAT_START = 'GET_CURRENT_CHAT_START';
export const GET_CURRENT_CHAT_SUCCESS = 'GET_CURRENT_CHAT_SUCCESS';
export const GET_CURRENT_CHAT_FAILED = 'GET_CURRENT_CHAT_FAILED';
export const SEND_MESSAGE_START = 'SEND_MESSAGE_START';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILED = 'SEND_MESSAGE_FAILED';
export const ADD_TEACHER_REVIEW_START = 'ADD_TEACHER_REVIEW_START';
export const ADD_TEACHER_REVIEW_SUCCESS = 'ADD_TEACHER_REVIEW_SUCCESS';
export const ADD_TEACHER_REVIEW_FAILED = 'ADD_TEACHER_REVIEW_FAILED';
export const GET_GROUP_TAGS_START = 'GET_GROUP_TAGS_START';
export const GET_GROUP_TAGS_SUCCESS = 'GET_GROUP_TAGS_SUCCESS';
export const GET_GROUP_TAGS_FAILED = 'GET_GROUP_TAGS_FAILED';
export const FINISH_COURSE_START = 'FINISH_COURSE_START';
export const FINISH_COURSE_SUCCESS = 'FINISH_COURSE_SUCCESS';
export const FINISH_COURSE_FAILED = 'FINISH_COURSE_FAILED';
