/*
 *
 * GroupPage constants
 *
 */

export const GET_GROUP_DATA_START = 'GET_GROUP_DATA_START';
export const GET_GROUP_DATA_SUCCESS = 'GET_GROUP_DATA_SUCCESS';
export const GET_GROUP_DATA_FAILED = 'GET_GROUP_DATA_FAILED';
export const ENTER_GROUP_START = 'ENTER_GROUP_START';
export const ENTER_GROUP_SUCCESS = 'ENTER_GROUP_SUCCESS';
export const ENTER_GROUP_FAILED = 'ENTER_GROUP_FAILED';
export const LEAVE_GROUP_START = 'LEAVE_GROUP_START';
export const LEAVE_GROUP_SUCCESS = 'LEAVE_GROUP_SUCCESS';
export const LEAVE_GROUP_FAILED = 'LEAVE_GROUP_FAILED';
